module.exports = [
    `seorang Macan Putih yang sangat ganas dan siap melindungi pemiliknya dari segala mara bahaya.`,
    `sesosok Harimau Loreng yang memiliki kekuatan luar biasa sebagai penjaga setia di setiap langkah hidupnya.`,
    `seekor Naga Emas yang membawa keberuntungan dan kekayaan tiada henti sepanjang hidupnya.`,
    `sosok Kera Sakti yang cerdik dan lincah, selalu menemani dalam menghadapi segala rintangan hidup.`,
    `siluman Ular yang mampu menghalau segala niat jahat dan serangan gaib yang mengancamnya.`,
    `seorang Bidadari Penjaga yang selalu memberi berkah, ketenangan, dan perlindungan di setiap waktu.`,
    `pendekar Tanpa Bayangan yang tak terlihat oleh musuh dan selalu hadir di saat-saat sulit.`,
    `Ratu Pantai Selatan yang memberikan pesona luar biasa dan daya tarik kuat bagi siapa saja yang melihatnya.`,
    `rajawali Sakti yang selalu terbang tinggi mengawasi dan menjaga dari atas langit.`,
    `Mbah Dukun sakti yang menjadi penasehat spiritual, membimbing dalam setiap keputusan penting.`,
    `Tuyul kecil yang selalu membantu memperlancar rezeki pemiliknya tanpa diketahui orang lain.`,
    `Genderuwo besar berbulu lebat yang siap menakut-nakuti musuh yang berniat jahat.`,
    `Jin Ifrit dari golongan api yang kuat dan bisa membakar semua niat jahat yang mengancam.`,
    `siluman Harimau Sakti penjaga garis keturunan keluarga secara turun-temurun.`,
    `Jin Penunggu Pohon yang setia menjaga harta benda dan keselamatan pemiliknya.`,
    `Sosok Bayangan Hitam yang selalu mengintai dan mengusir roh jahat yang mendekat.`,
    `Jin Keturunan Raja yang memiliki wibawa luar biasa dan membawa keberuntungan besar.`,
    `Siluman Serigala yang cerdik, cepat, dan ganas dalam menjaga serta memburu musuh.`,
    `Mahluk Halus Penjaga Warisan Leluhur yang selalu hadir saat pemiliknya dalam kesulitan.`,
    `Siluman Naga Laut yang menjaga dari segala marabahaya di daratan maupun lautan.`,
    `Kuntilanak putih yang justru menjadi pelindung dari serangan gaib dan ilmu hitam.`,
    `Pendekar Pedang Sakti yang selalu siap menebas musuh dan gangguan tak kasat mata.`,
    `Kera Putih penjaga yang lincah dan memiliki kekuatan supranatural luar biasa.`,
    `Pocong Sakti yang justru menjadi perantara keberuntungan dan rezeki bagi pemiliknya.`,
    `Siluman Buaya Putih penjaga sungai dan segala tempat berair, menjaga dari musibah air.`,
    `Rajawali Putih besar yang selalu mengawasi dari udara dan membawa kabar baik.`,
    `Dewi Penjaga Pintu Rezeki yang membuka jalan rezeki dari berbagai arah tanpa henti.`,
    `Siluman Macan Hitam yang buas dan hanya tunduk kepada pemiliknya.`,
    `Roh Leluhur yang selalu membimbing jalan hidup dan memberi perlindungan tak terlihat.`,
    `Siluman Gajah sakti pembawa keberuntungan, kekuatan, dan kejayaan.`,
    `Pendeta tua penjaga kebijaksanaan dan memberikan petunjuk di saat-saat sulit.`,
    `Jin Pasukan Gaib yang siap menyerang siapa saja yang berani mengganggu pemiliknya.`,
    `Penunggu Keris Sakti yang menjaga keselamatan dan menambah wibawa pemiliknya.`,
    `Siluman Ular Hijau penjaga harta dan pelindung dari santet serta teluh.`,
    `Kuntilanak Merah yang justru membawa keberuntungan dalam dunia usaha dan dagang.`,
    `Siluman Kucing Hitam yang cerdik dan mampu mengubah nasib pemiliknya.`,
    `Prabu Gaib penjaga kerajaan astral yang memberikan kekuatan supranatural kepada pemiliknya.`,
    `Siluman Kuda Hitam yang mampu membawa pemiliknya ke mana pun dalam dunia astral.`,
    `Dewa Rezeki yang selalu menyertai dan melimpahkan kekayaan tanpa henti.`,
    `Siluman Rusa Putih yang membawa ketentraman, keberuntungan, dan kedamaian hidup.`,
    `Ratu Kembang Setaman yang harum mewangi dan menjaga pesona serta keberuntungan pemiliknya.`,
    `Siluman Elang Hitam yang terbang tinggi membawa kabar baik dan menghalau bahaya.`,
    `Penjaga Gerbang Alam Gaib yang memastikan keselamatan pemiliknya dari serangan astral.`,
    `Siluman Ular Merah penjaga kekayaan dan pelindung dari segala kejahatan ilmu hitam.`,
    `Prajurit Gaib kerajaan Majapahit yang siap berperang demi keselamatan pemiliknya.`,
    `Siluman Monyet Hitam yang lincah dan mampu mencuri rahasia musuh secara halus.`,
    `Putri Gaib dari Gunung Lawu yang memberikan kesaktian dan keberuntungan dalam dagang.`,
    `Siluman Burung Hantu Penjaga Malam yang selalu waspada dari serangan musuh.`,
    `Satria Piningit yang diramalkan akan membawa kejayaan dan keberuntungan besar.`
];