module.exports = [
  "Tahukah kamu? Madu adalah satu-satunya makanan yang tidak pernah basi.",
  "Tahukah kamu? Gurita punya tiga jantung dan darah berwarna biru.",
  "Tahukah kamu? Jerapah hanya butuh tidur sekitar 30 menit sehari.",
  "Tahukah kamu? Indonesia punya lebih dari 17.000 pulau.",
  "Tahukah kamu? Air terjun tertinggi di dunia adalah Angel Falls di Venezuela.",
  "Tahukah kamu? Kucing nggak bisa merasakan rasa manis.",
  "Tahukah kamu? Manusia berbagi sekitar 60% DNA-nya dengan pisang.",
  "Tahukah kamu? Hiu adalah satu-satunya ikan yang bisa mengedipkan kedua matanya.",
  "Tahukah kamu? Burung kolibri satu-satunya burung yang bisa terbang mundur.",
  "Tahukah kamu? Planet Saturnus bisa mengapung di air karena massanya lebih ringan dari air.",
  "Tahukah kamu? Jantung manusia berdetak sekitar 100.000 kali per hari.",
  "Tahukah kamu? Bumi berputar dengan kecepatan sekitar 1.670 km/jam di khatulistiwa.",
  "Tahukah kamu? Emoji pertama kali muncul di Jepang pada tahun 1999.",
  "Tahukah kamu? Laut Mati memiliki kadar garam 9 kali lebih tinggi dari lautan biasa.",
  "Tahukah kamu? Semut bisa mengangkat beban 50 kali berat tubuhnya.",
  "Tahukah kamu? Air panas bisa membeku lebih cepat dari air dingin, disebut efek Mpemba.",
  "Tahukah kamu? Badak punya kulit setebal 5 cm tapi sensitif terhadap gigitan serangga.",
  "Tahukah kamu? Lebah harus mengunjungi sekitar 2 juta bunga untuk menghasilkan satu pon madu.",
  "Tahukah kamu? Tulang manusia lima kali lebih kuat dari baja dengan berat yang sama.",
  "Tahukah kamu? Bola lampu ditemukan oleh Thomas Edison pada tahun 1879.",
  "Tahukah kamu? Lumba-lumba tidur dengan satu mata terbuka.",
  "Tahukah kamu? Kecepatan bersin manusia bisa mencapai 160 km/jam.",
  "Tahukah kamu? 80% gunung berapi dunia ada di Cincin Api Pasifik.",
  "Tahukah kamu? Planet Venus berputar ke arah berlawanan dari planet lainnya.",
  "Tahukah kamu? Zebra sebenarnya punya kulit hitam dengan garis putih.",
  "Tahukah kamu? Tanduk badak terbuat dari keratin, sama seperti rambut dan kuku manusia.",
  "Tahukah kamu? Burung unta punya mata lebih besar dari otaknya.",
  "Tahukah kamu? Gigi manusia sekeras batu permata.",
  "Tahukah kamu? Buaya bisa hidup tanpa makan lebih dari setahun.",
  "Tahukah kamu? Gunung Everest bertambah tinggi sekitar 4 mm per tahun.",
  "Tahukah kamu? Satu sendok teh tanah mengandung lebih banyak mikroorganisme daripada jumlah manusia di bumi.",
  "Tahukah kamu? Otak manusia bisa menyimpan informasi 2,5 petabyte, setara 3 juta jam video.",
  "Tahukah kamu? Jangkrik menghitung suhu lewat suara 'kring-kring'-nya.",
  "Tahukah kamu? Bola mata manusia ukuran tetap sejak lahir, tapi hidung dan telinga terus tumbuh.",
  "Tahukah kamu? Titanic butuh waktu 2 jam lebih untuk tenggelam.",
  "Tahukah kamu? Gajah bisa deteksi getaran lewat kakinya dari jarak kilometer.",
  "Tahukah kamu? Matahari berdiameter 109 kali lebih besar dari Bumi.",
  "Tahukah kamu? Paus biru adalah hewan terbesar yang pernah hidup di bumi.",
  "Tahukah kamu? Tembok Besar China tidak terlihat dari luar angkasa pakai mata telanjang, itu mitos.",
  "Tahukah kamu? Setiap manusia punya bau badan unik kecuali kembar identik.",
  "Tahukah kamu? Pembuluh darah manusia bisa mengelilingi bumi 2,5 kali jika disambung.",
  "Tahukah kamu? Kupu-kupu bisa mencium bau dari jarak lebih dari 2 km.",
  "Tahukah kamu? Rata-rata manusia berjalan setara 5 kali keliling bumi sepanjang hidupnya.",
  "Tahukah kamu? Hewan capung sudah ada sejak zaman dinosaurus.",
  "Tahukah kamu? Rusa tidak punya kantung empedu.",
  "Tahukah kamu? Otak manusia pakai 20% energi tubuh meski beratnya cuma 2% dari tubuh.",
  "Tahukah kamu? Di Kutub Utara, matahari bisa terbit selama 6 bulan tanpa terbenam.",
  "Tahukah kamu? Lebah bisa mengenali wajah manusia.",
  "Tahukah kamu? Makanan pedas memicu hormon endorfin, bikin nagih.",
  "Tahukah kamu? Sidik lidah manusia sama uniknya dengan sidik jari.",
  "Tahukah kamu? Gurun Sahara dulunya adalah lautan.",
  "Tahukah kamu? Jamur terbesar di dunia beratnya lebih dari 400 ton.",
  "Tahukah kamu? Pohon tertua di dunia berumur lebih dari 5.000 tahun.",
  "Tahukah kamu? Kura-kura bisa hidup lebih dari 150 tahun.",
  "Tahukah kamu? Lebih dari 70% oksigen di bumi berasal dari lautan.",
  "Tahukah kamu? Di luar angkasa, astronot nggak bisa bersin.",
  "Tahukah kamu? Astronot lebih tinggi 5 cm saat di luar angkasa karena tidak ada gravitasi.",
  "Tahukah kamu? Cacing bisa punya hingga 10 hati.",
  "Tahukah kamu? Otak manusia menghasilkan listrik yang cukup untuk menyalakan bola lampu kecil.",
  "Tahukah kamu? Unta bisa minum 100 liter air dalam sekali minum.",
  "Tahukah kamu? Burung hantu bisa memutar kepalanya hingga 270 derajat.",
  "Tahukah kamu? Listrik pertama kali ditemukan oleh Benjamin Franklin tahun 1752.",
  "Tahukah kamu? Rekor manusia terlama nggak tidur adalah 11 hari.",
  "Tahukah kamu? Air laut beku menjadi es yang rasanya tawar.",
  "Tahukah kamu? Bola basket awalnya terbuat dari bola sepak.",
  "Tahukah kamu? Bulan secara perlahan menjauh dari bumi sekitar 3,8 cm per tahun.",
  "Tahukah kamu? Rekor suhu terpanas di bumi adalah 56,7°C di Furnace Creek Ranch, Death Valley, AS.",
  "Tahukah kamu? Sejak 2011, lebih banyak orang mati akibat selfie daripada serangan hiu.",
  "Tahukah kamu? Sapi punya sahabat dan bisa stres kalau dipisah.",
  "Tahukah kamu? Air kelapa bisa digunakan sebagai pengganti cairan infus.",
  "Tahukah kamu? Orang Eskimo punya lebih dari 50 kata untuk menggambarkan salju.",
  "Tahukah kamu? Lebah tidak akan bisa terbang kalau mengikuti hukum aerodinamika manusia.",
  "Tahukah kamu? Di Jepang ada hotel tertua di dunia yang sudah berdiri sejak tahun 705 Masehi.",
  "Tahukah kamu? Permukaan Venus lebih panas dari Merkurius meski lebih jauh dari matahari.",
  "Tahukah kamu? Bahasa tertua yang masih digunakan sampai sekarang adalah Bahasa Tamil.",
  "Tahukah kamu? Kita menghabiskan sekitar 6 bulan dari hidup hanya untuk menunggu lampu merah.",
  "Tahukah kamu? Satu juta detik sama dengan 11 hari, tapi satu miliar detik sama dengan 31 tahun.",
  "Tahukah kamu? Perut kita menghasilkan lapisan lendir baru setiap 2 minggu agar tidak mencerna dirinya sendiri.",
  "Tahukah kamu? Ada lebih dari 200 mayat yang tersisa di Gunung Everest dan sekarang jadi penunjuk arah.",
  "Tahukah kamu? Gitar listrik pertama kali diperkenalkan tahun 1931.",
  "Tahukah kamu? Pinguin jantan melamar betinanya dengan batu kecil.",
  "Tahukah kamu? Hidung manusia bisa mencium lebih dari 1 triliun aroma berbeda."
];